### PR TITLE
Update download strings in Notebook

### PR DESCRIPTION
**Pull request by TheLostLambda**
Fixes a typo and removes some outdated information

PS. The new notebook is great! Thanks for all of the hard work @ns-rse !

### CODE REVIEW

**Review by bobturneruk — APPROVED** [review]
Good spot.

**Comment by TheLostLambda** [comment]
Could I pester @ns-rse for merge permissions on this repo?

**Comment by bobturneruk** [comment]
@TheLostLambda - you're now an org owner.

**Review by ns-rse — APPROVED** [review]
Good spot, thanks @TheLostLambda

**Comment by ns-rse** [comment]
> Could I pester @ns-rse for merge permissions on this repo?

Added/invited you to this repo with admin permissions @TheLostLambda

**Pull request merged**
